name: Api Build And Publish With Docker
on: push

jobs:
  build:
    name: build .net core app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: |
        pwd
        ls
    - run: |
        docker build -t  ${{ secrets.DOCKER_USERNAME }}/test ./
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/test

    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: 22
        script: |
          docker stop $(docker ps --filter ancestor=${{ secrets.DOCKER_USERNAME }}/test -q)
          docker rm -f $(docker ps -a --filter ancestor=${{ secrets.DOCKER_USERNAME }}/test:latest -q)
          docker rmi -f $(docker images ${{ secrets.DOCKER_USERNAME }}/test:latest -q)
          #docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/test
          docker run -d -p 5371:80 ${{ secrets.DOCKER_USERNAME }}/test

        
