name: TestActions
on: 
  [ push ]

jobs:
  job_01:
    name: build docker & deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - run: |
        docker build -t  ${{ secrets.DOCKER_USERNAME }}/test ./
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/test

    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: 22
        script: |
          repo_01=${{ secrets.DOCKER_USERNAME }}/test
          docker stop $(docker ps --filter ancestor=${repo_01} -q)
          docker rm -f $(docker ps -a --filter ancestor=${repo_01}  -q)
          docker rmi -f $(docker images ${repo_01}  -q)
          docker pull ${repo_01} 
          docker run -d -p 5371:80 ${repo_01} 

        
