name: Api Build And Publish With Docker
on: push

jobs:
  build:
    name: build .net core app
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@main
    #- uses: actions/setup-dotnet@v1
    #- run: dotnet restore
    #- run: dotnet publish -c Release

    - run: pwd
    - name: Publish to Docker Repository
      #uses: elgohr/Publish-Docker-Github-Action@master
      #with:
      #  name: studiera/test
      #  username: studiera
      #  password: ${{ secrets.DOCKER_PASSWORD }}
      run: docker build -t studiera/test:latest ./
    - run: docker login --username=studiera --password ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push studiera/test:latest

