name: Api Build And Publish With Docker
on: push

jobs:
  build:
    name: build .net core app
    runs-on: ubuntu-latest
    steps:
    - name: pull code
      uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5'
    - name: restore dependencies
      run: dotnet restore