name: Api Build And Publish With Docker
on: push

jobs:
  build:
    name: build .net core app
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@main
    #- uses: actions/setup-dotnet@v1
    #- run: dotnet restore
    #- run: dotnet publish -c Release

    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: studiera/test
        username: studiera
        password: ${{ secrets.DOCKER_PASSWORD }}
